sprin-2710 adding stronger typing. also seperated util functions into…
DAAily/daailyapis-python-client pull request #24
Opened 2024-12-06 09:14 UTC by Sylver11

… resources and added generator approach to manufacturer get function. Would also need to be addded to all of the other util functions. Also improving examples

2024-12-06 10:55 UTC, axelmukwena commented
Just to understand, `resources` are where REST views are defined, and `client` is the base HTTP client that allows you to send requests and receive data?

2024-12-06 13:15 UTC, KeanuDaaily commented on daaily/lucy/resources.py
> +    def get(
Please keep the resources standardized, change this to be like all the others, or implement this approach for the other resources.

2024-12-06 13:16 UTC, KeanuDaaily commented on daaily/lucy/response.py
> +import json
The file contents seem to be duplicated to the `daaily/franklin/response.py` file as well, can you centralize this please.

2024-12-06 13:17 UTC, KeanuDaaily requested changes
Overall looks really good, I left a few notes.

2024-12-09 08:21 UTC, Sylver11 commented on daaily/franklin/response.py
its a stub essentially. given that we will be able to use other transport classes its another safety measure to ensure correct types.

2024-12-09 08:25 UTC, Sylver11 commented on daaily/lucy/client.py
>      def get_paginated_entities(
if the user only wants 2000 entities they would only need to break the yield for loop on count 2000. 

the get_paginatated_entities will serve a different purpose. It will be the approach we take when we do async requests and where the user needs to get all of the entities first before running manipulations. Will also be faster than the yielding appraoch.

2024-12-09 08:27 UTC, Sylver11 commented on daaily/lucy/response.py
> +import json
this is on purpose. We want to ensure type safety. Its a sort of duplication but makes the code more readable in my opinion

2024-12-09 08:28 UTC, Sylver11 commented on daaily/lucy/resources.py
> +    def get(
yes that is just a lot of work. Will create a another task for that and tackle it separately.

2024-12-09 08:29 UTC, Sylver11 commented
> Just to understand, `resources` are where REST views are defined, and `client` is the base HTTP client that allows you to send requests and receive data?

correct. But at the same time the client also allows you to go a bit "deeper" in case you need to do something more special

2024-12-09 08:41 UTC, axelmukwena approved these changes
Okay, all good them from my side

2024-12-09 13:16 UTC, merged